name: Update APT Repository

on:
  push:
    branches:
      - main
    paths:
      - '**/*.deb'

jobs:
  update-packages:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Setup Git config
      run: |
        git config user.name "github-actions"
        git config user.email "github-actions@github.com"

    - name: Generate Packages.gz
      run: |
        dpkg-scanpackages . /dev/null | gzip -9c > Packages  
        git add Packages
        git commit -m "Update Packages"
        git push
