name: Обновление APT репозитория

on:
  push:
    branches:
      - main
    paths:
      - '**/*.deb'

jobs:
  update-packages:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Настройка Git конфигурации
      run: |
        git config user.name "github-actions"
        git config user.email "github-actions@github.com"

    - name: Установка необходимых пакетов
      run: sudo apt-get update && sudo apt-get install -y dpkg-dev apt-utils gnupg

    - name: Импорт GPG ключа
      run: |
        echo "${{ secrets.GPG_PRIVATE_KEY }}" | gpg --import

    - name: Генерация и подписание файла Packages
      run: |
        dpkg-scanpackages --multiversion . /dev/null | tee Packages
        cat Packages
        rm -f Packages.gpg
        gpg --batch --pinentry-mode loopback --default-key ${{ secrets.GPG_KEY_ID }} --output Packages.gpg --detach-sign Packages

    - name: Генерация и подписание файла Release
      run: |
        apt-ftparchive release . | tee Release
        rm -f Release.gpg
        gpg --batch --pinentry-mode loopback --armor --default-key ${{ secrets.GPG_KEY_ID }} --output Release.gpg --detach-sign Release

    - name: Фиксация изменений и публикация в репозиторий
      run: |
        git add .
        git commit -am "Автоматическое обновление файлов Packages и Release" || echo "Нет изменений для коммита."
        git push origin main --force-with-lease
